### ISSUE TITLE
feat(overall): doug can see this repo

### ISSUE THREAD

**Issue by snoopdouglas** [Freeformers/jsbin#7]
Is this still meant to be the case? :p 

[ff-config](https://github.com/Freeformers/ff-config) is also visible to me, though I can only see the master branch and (luckily) no creds.

@shauns hope you're enjoying FF - sorry to leave you such a horrible legacy in the form of the old feedback system...

**Comment by shauns** [comment]
Thanks for dropping us a line -- its a public one though, so you're not the only person who can have a look!

**Comment by shauns** [comment]
WONTFIX ;)

**Comment by snoopdouglas** [comment]
Haha, cheers ;)
